const API_BASE_URL=window.AdminAuth.apiBaseUrl;const session=window.AdminAuth.requireAdmin();const token=session?.token;let users=[];
const body=document.querySelector("#users-body"),search=document.querySelector("#user-search"),roleFilter=document.querySelector("#role-filter"),statusFilter=document.querySelector("#status-filter");
search.addEventListener("input",renderUsers);roleFilter.addEventListener("change",renderUsers);statusFilter.addEventListener("change",renderUsers);window.addEventListener("admin-global-search",event=>{search.value=event.detail;renderUsers()});document.querySelector("#add-user").addEventListener("click",openAddUser);loadUsers();
async function loadUsers(){try{const response=await fetch(`${API_BASE_URL}/api/admin/resources/users`,{headers:{Authorization:`Bearer ${token}`}});if([401,403].includes(response.status))return window.AdminAuth.clearSession();const result=await response.json();if(!response.ok)throw new Error(result.message);users=result.records;setText("total-users",users.length);setText("total-students",countRole("STUDENT"));setText("total-instructors",countRole("INSTRUCTOR"));setText("total-admins",countRole("ADMIN"));renderUsers()}catch(error){showMessage(error.message||"Unable to load users")}}
function renderUsers(){const term=search.value.toLowerCase().trim(),role=roleFilter.value,state=statusFilter.value;const filtered=users.filter(user=>(!term||`${user.name} ${user.email}`.toLowerCase().includes(term))&&(role==="ALL"||user.role===role)&&(state==="ALL"||(state==="ACTIVE")===Boolean(user.isActive)));body.innerHTML=filtered.length?filtered.map(userRow).join(""):'<tr class="empty-row"><td colspan="8">No users match these filters.</td></tr>';document.querySelector("#user-result-count").textContent=`Showing ${filtered.length} of ${users.length} users`;body.querySelectorAll("[data-edit]").forEach(button=>button.addEventListener("click",()=>openEditUser(users.find(user=>user.id===Number(button.dataset.edit)))));body.querySelectorAll("[data-delete]").forEach(button=>button.addEventListener("click",()=>confirmDeleteUser(users.find(user=>user.id===Number(button.dataset.delete)))))}
function userRow(user){return `<tr><td><div class="user-cell"><span class="small-avatar">${escapeHtml(user.firstName.charAt(0))}</span><span><strong>${escapeHtml(user.name)}</strong><small>${escapeHtml(user.email)}</small></span></div></td><td><span class="badge role">${label(user.role)}</span></td><td>${escapeHtml(user.phone||"—")}</td><td><span class="badge ${user.isActive?"active":"inactive"}">${user.isActive?"Active":"Inactive"}</span></td><td><span class="badge ${user.emailVerifiedAt?"verified":"unverified"}">${user.emailVerifiedAt?"Verified":"Not verified"}</span></td><td>${date(user.lastLoginAt)}</td><td>${date(user.createdAt)}</td><td><div class="actions"><button data-edit="${user.id}" type="button" title="Edit user">✎</button><button data-delete="${user.id}" type="button" title="Delete user">⌫</button></div></td></tr>`}
function fields(user){return[{name:"firstName",label:"First Name",required:true,value:user?.firstName},{name:"lastName",label:"Last Name",required:true,value:user?.lastName},{name:"email",label:"Email Address",type:"email",required:true,value:user?.email},{name:"password",label:"Temporary Password",type:"password",required:!user,placeholder:user?"Unchanged":"At least 8 characters",hint:user?"Password is not changed here":"Share it securely with the user"},{name:"role",label:"Role",type:"select",required:true,value:user?.role||"STUDENT",options:[{value:"STUDENT",label:"Student"},{value:"INSTRUCTOR",label:"Instructor"},{value:"ADMIN",label:"Administrator"}]},{name:"phone",label:"Phone",type:"tel",value:user?.phone},{name:"bio",label:"Bio",type:"textarea",full:true,value:user?.bio,rows:3},{name:"isActive",label:"Account is active",type:"checkbox",full:true,checked:user?Boolean(user.isActive):true}]}
function openAddUser(){window.AdminModal.openForm({title:"Add New User",submitLabel:"Create User",fields:fields(),onSubmit:async data=>{const result=await send("/api/admin/users","POST",data);await loadUsers();window.AdminModal.showSuccess({title:"User Added Successfully!",message:`${result.user.firstName} ${result.user.lastName} can now access the platform.`,primaryLabel:"Add Another User",secondaryLabel:"View Users",onPrimary:openAddUser})}})}
function openEditUser(user){const editFields=fields(user).filter(field=>field.name!=="password");window.AdminModal.openForm({title:"Edit User",submitLabel:"Save Changes",fields:editFields,onSubmit:async data=>{await send(`/api/admin/users/${user.id}`,"PATCH",data);await loadUsers();window.AdminModal.showSuccess({title:"User Updated Successfully!",message:`${user.name}'s account changes have been saved.`,primaryLabel:"Done"})}})}
function confirmDeleteUser(user){window.AdminModal.confirm({title:"Delete User?",message:`This permanently deletes ${user.name} and related learning records. This cannot be undone.`,confirmLabel:"Delete User",onConfirm:async()=>{await send(`/api/admin/users/${user.id}`,"DELETE");await loadUsers();showMessage(`${user.name} was deleted.`)}})}
async function send(path,method,data){const response=await fetch(API_BASE_URL+path,{method,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();if([401,403].includes(response.status))return window.AdminAuth.clearSession();if(!response.ok)throw new Error(result.message||"Unable to save user");return result}
function countRole(role){return users.filter(user=>user.role===role).length}function setText(id,value){document.querySelector(`#${id}`).textContent=value.toLocaleString()}function label(value){return value.toLowerCase().replace(/\b\w/g,l=>l.toUpperCase())}function date(value){return value?new Intl.DateTimeFormat("en-ZA",{dateStyle:"medium"}).format(new Date(value)):"—"}function showMessage(text){const element=document.querySelector("#user-message");element.textContent=text;element.classList.add("show")}function escapeHtml(value){const element=document.createElement("span");element.textContent=String(value);return element.innerHTML}
