const { Router } = require("express");
const { authenticate, authorizeRoles } = require("../middleware/auth.middleware");
const { getDashboard, getCourses, createCourse, updateCourse, deleteCourse, getLessons, createLesson, updateLesson, deleteLesson, getEnrollments, createEnrollment, updateEnrollment, deleteEnrollment, getProgress, updateProgressAdmin, deleteProgressAdmin, getActivities, createActivity, updateActivity, deleteActivity, getAnnouncements, createAnnouncement, updateAnnouncement, deleteAnnouncement, getMessages, createMessage, updateMessage, deleteMessage, getNotifications, createNotification, updateNotification, deleteNotification, getReports, getSettings, createSetting, updateSetting, deleteSetting, getAuditLogs, createUser, updateUser, deleteUser, getResource } = require("../controllers/admin.controller");

const router = Router();

router.use(authenticate, authorizeRoles("ADMIN"));
router.get("/dashboard", getDashboard);
router.get("/courses", getCourses);
router.post("/courses", createCourse);
router.patch("/courses/:id", updateCourse);
router.delete("/courses/:id", deleteCourse);
router.get("/lessons", getLessons);
router.post("/lessons", createLesson);
router.patch("/lessons/:id", updateLesson);
router.delete("/lessons/:id", deleteLesson);
router.get("/enrollments", getEnrollments);
router.post("/enrollments", createEnrollment);
router.patch("/enrollments/:id", updateEnrollment);
router.delete("/enrollments/:id", deleteEnrollment);
router.get("/progress", getProgress);
router.patch("/progress/:id", updateProgressAdmin);
router.delete("/progress/:id", deleteProgressAdmin);
router.get("/activities", getActivities);
router.post("/activities", createActivity);
router.patch("/activities/:id", updateActivity);
router.delete("/activities/:id", deleteActivity);
router.get("/announcements", getAnnouncements);
router.post("/announcements", createAnnouncement);
router.patch("/announcements/:id", updateAnnouncement);
router.delete("/announcements/:id", deleteAnnouncement);
router.get("/messages", getMessages);
router.post("/messages", createMessage);
router.patch("/messages/:id", updateMessage);
router.delete("/messages/:id", deleteMessage);
router.get("/notifications", getNotifications);
router.post("/notifications", createNotification);
router.patch("/notifications/:id", updateNotification);
router.delete("/notifications/:id", deleteNotification);
router.get("/reports", getReports);
router.get("/settings", getSettings);
router.post("/settings", createSetting);
router.patch("/settings/:id", updateSetting);
router.delete("/settings/:id", deleteSetting);
router.get("/audit-logs", getAuditLogs);
router.post("/users", createUser);
router.patch("/users/:id", updateUser);
router.delete("/users/:id", deleteUser);
router.get("/resources/:resource", getResource);

module.exports = router;
